### PR TITLE
Add changelog

### PR DESCRIPTION
**Pull request by axlon**

### CODE REVIEW

**Comment by axlon** [comment]
Hold off on this PR until #17 has been merged into master, I thought 0.2.0 had been tagged but its a branch, so the date in the changelog will have to be changed as well.

**Comment by yak0d3** [comment]
I think we should finish with the [**Default Configuration**](https://github.com/LaraCrafts/laravel-geo-routes/tree/config-defaults) and the [**GeoGroups**](https://github.com/LaraCrafts/laravel-geo-routes/tree/geo-groups) before releasing **v0.2.0**

**Comment by axlon** [comment]
I disagree, I'd say that once we have those features, we'd be ready to release our first RC for 1.0.0

**Comment by yak0d3** [comment]
> 
> 
> I disagree, I'd say that once we have those features, we'd be ready to release our first RC for 1.0.0

It would be very unsafe to release an rc just after adding such big features

**Pull request merged**
